### ISSUE TITLE
An Issue with the Linter

### ISSUE THREAD

**Issue by theednaffattack** [Sly777/ran#198]
Hi,

I'm having difficulty running this in dev mode.  It's definitely something to do with ESLint, but I'm not sure how to address the issue it's highlighting.

In order to run properly I had to edit package.json to remove the linting, but that's not a long-term solution.

I'm still new to ESLint but I'm used to errors pointing to some kind of ruleset that I can look up online which will teach me how to find and fix it in my project. In this case I'm either missing this instruction or it's absent.  Any insight or tips you can provide are greatly appreciated.

This is a fresh git clone using Node 8.6.0, npm 5.3.0

I'm also using Mac OS 10.12.6, if that's a factor.

```shell
npm run dev

> ran-boilerplate@0.6.0 dev /Users/eddienaff/Documents/Projects/personal/learning/demos/apollo-graphql/RAN
> npm run lint && npm run clean-cache && node server.js


> ran-boilerplate@0.6.0 lint /Users/eddienaff/Documents/Projects/personal/learning/demos/apollo-graphql/RAN
> eslint --fix --ext .gql --ext .graphql --ext .js pages components containers libraries server helper_scripts

Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.
Error: Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.
    at invariant (/Users/eddienaff/Documents/Projects/personal/learning/demos/apollo-graphql/RAN/node_modules/eslint-plugin-graphql/node_modules/graphql/jsutils/invariant.js:19:11)
    at validate (/Users/eddienaff/Documents/Projects/personal/learning/demos/apollo-graphql/RAN/node_modules/eslint-plugin-graphql/node_modules/graphql/validation/validate.js:60:72)
    at handleTemplateTag (/Users/eddienaff/Documents/Projects/personal/learning/demos/apollo-graphql/RAN/node_modules/eslint-plugin-graphql/lib/index.js:410:57)
    at TaggedTemplateExpression (/Users/eddienaff/Documents/Projects/personal/learning/demos/apollo-graphql/RAN/node_modules/eslint-plugin-graphql/lib/index.js:126:20)
    at listeners.(anonymous function).forEach.listener (/Users/eddienaff/Documents/Projects/personal/learning/demos/apollo-graphql/RAN/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/eddienaff/Documents/Projects/personal/learning/demos/apollo-graphql/RAN/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/Users/eddienaff/Documents/Projects/personal/learning/demos/apollo-graphql/RAN/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/eddienaff/Documents/Projects/personal/learning/demos/apollo-graphql/RAN/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/eddienaff/Documents/Projects/personal/learning/demos/apollo-graphql/RAN/node_modules/eslint/lib/util/node-event-generator.js:294:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ran-boilerplate@0.6.0 lint: `eslint --fix --ext .gql --ext .graphql --ext .js pages components containers libraries server helper_scripts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ran-boilerplate@0.6.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eddienaff/.npm/_logs/2017-10-02T19_45_39_406Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ran-boilerplate@0.6.0 dev: `npm run lint && npm run clean-cache && node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ran-boilerplate@0.6.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eddienaff/.npm/_logs/2017-10-02T19_45_39_427Z-debug.log
```

I thought it might be something to do with the .babelrc file but everything looks okay to me. Is it an error because I don't have any .graphql files in my project yet?

**Comment by Sly777** [comment]
hey @theednaffattack , It's fixed on latest version. Can you please test it again?

**Comment by theednaffattack** [comment]
Thanks! That fixed it.
