### ISSUE TITLE
Cannot find module 'figlet'

### ISSUE THREAD

**Issue by Obooman** [Sly777/ran#23]
Both `npm run setup` and `yarn run setup` cause this error.

macOS Sierra 10.12.5 (16F73)
```
node -v
v7.8.0
npm -v
5.0.3
```

error log
```bash
+ cli-clear@1.0.4
+ shelljs@0.7.8
removed 1141 packages and updated 17 packages in 33.767s
module.js:472
    throw err;
    ^

Error: Cannot find module 'figlet'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/Document/github/RAN/helper_scripts/CL_commands/__helpers.js:1:78)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
error Command failed with exit code 1.
info Visit http://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
I have tried `npm install figlet` or `yarn add figlet`,they all work well.
run `yarn run setup` after run `yarn add figlet` the issue keeps on.

**Comment by Sly777** [comment]
Hey @Obooman ! Thanks for your issue. I checked but did you run ```npm install``` before that command? It looks like you didn't install dependencies.

**Comment by Obooman** [comment]
Hi Ilker(nice dress😉),I have already run `yarn install` before run `yarn run setup` as README describe,100% sure,that's why it's strange.I'm showing all my commands and outputs below.

AND repeat it,`npm install figlet` single dependency goes well.

```bash
▲ ~ cd /Volumes/Document/github/RAN
▲ RAN at master ✖ yarn     
yarn install v0.15.1
warning ran-boilerplate@0.2.3: "dependencies" has dependency "figlet" with range "^1.2.0" that collides with a dependency in "devDependencies" of the same name with version "1.2.0"
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning Incorrect peer dependency "next@^2.x.x".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 203.55s.
▲ RAN at master ✖ yarn run setup
yarn run v0.15.1
$ npm run setup:before && node ./helper_scripts/CL_commands/setup.js && npm run setup:after 
npm WARN invalid config init-author-url="github.com/obooman"
npm WARN invalid config Must be a full url with 'http://'

> ran-boilerplate@0.2.3 setup:before /Volumes/Document/github/RAN
> npm i shelljs cli-clear


> pre-commit@1.2.2 uninstall /Volumes/Document/github/RAN/node_modules/pre-commit
> node uninstall.js


> husky@0.14.1 uninstall /Volumes/Document/github/RAN/node_modules/husky
> node ./bin/uninstall.js

husky
uninstalling Git hooks
done

npm WARN gentlyRm not removing /Volumes/Document/github/RAN/node_modules/decompress-zip/node_modules/touch/node_modules/.bin/nopt as it wasn't installed by /Volumes/Document/github/RAN/node_modules/decompress-zip/node_modules/touch/node_modules/nopt
npm WARN gentlyRm not removing /Volumes/Document/github/RAN/node_modules/acorn-globals/node_modules/.bin/acorn as it wasn't installed by /Volumes/Document/github/RAN/node_modules/acorn-globals/node_modules/acorn
npm WARN gentlyRm not removing /Volumes/Document/github/RAN/node_modules/acorn-dynamic-import/node_modules/.bin/acorn as it wasn't installed by /Volumes/Document/github/RAN/node_modules/acorn-dynamic-import/node_modules/acorn
npm WARN The package figlet is included as both a dev and production dependency.

+ shelljs@0.7.8
+ cli-clear@1.0.4
removed 1141 packages and updated 17 packages in 43.203s
module.js:472
    throw err;
    ^

Error: Cannot find module 'figlet'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/Document/github/RAN/helper_scripts/CL_commands/__helpers.js:1:78)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
error Command failed with exit code 1.
info Visit http://yarnpkg.com/en/docs/cli/run for documentation about this command.
▲ RAN at master ✖ 

```

**Comment by Sly777** [comment]
Thanks for the error log, @Obooman! hmmm, the weird thing is I followed same steps on mac and Linux but I couldn't get the same error. I saw somehow It uninstalls "pre-commit" and "husky". Also **yarn** looks older version than mine. I'm using yarn **v0.24.6** so If it's possible, can you update yarn and try again?

**Comment by Sly777** [comment]
Hey @Obooman, I found the bug on node.js v8. I don't know why It's uninstalling some packages on node.js v8. I will work on that.

**Comment by Sly777** [comment]
Last Update 😄 
I pushed hotfix for node.js v8 now. I tested on v8.1.3 and It works but can you also test it, please?

**Comment by Obooman** [comment]
Hi,Have checked current `master` branch and it works weel,good job!
