### ISSUE TITLE
Cannot find module 'figlet'

### ISSUE THREAD

**Issue by mehdijjz** [Sly777/ran#25]
After a clean installation, I get this error when running `yarn run setup`:

`Error: Cannot find module 'figlet'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mehdijjz/Development/Projects/RAN/helper_scripts/CL_commands/__helpers.js:1:78)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)`

**Comment by Sly777** [comment]
Hi @mehdijjz, Did you run ```yarn install``` before running that command? And also did you check devDependencies installed? When you run ```yarn run setup``` before ```yarn install```, It's giving ***cannot find module `figlet`*** error.

**Comment by mehdijjz** [comment]
yes of course I ran yarn install. I have tried yarn version 24.5 and 27.5 and it's not working in any of them. my node version is 8.1.2 and here is my error log

`➜  Projects git clone --depth=1 https://github.com/Sly777/ran.git RAN
Cloning into 'RAN'...
remote: Counting objects: 77, done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 77 (delta 4), reused 46 (delta 4), pack-reused 0
Unpacking objects: 100% (77/77), done.
➜  Projects cd RAN 
➜  RAN git:(master) yarn install     
yarn install v0.24.5
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "next-url-prettifier@1.1.4" has incorrect peer dependency "next@^2.x.x".
[4/4] 📃  Building fresh packages...
✨  Done in 41.94s.
➜  RAN git:(master) yarn run setup
yarn run v0.24.5
$ npm run setup:before && node ./helper_scripts/CL_commands/setup.js && npm run setup:after 

> ran-boilerplate@0.2.3 setup:before /Users/mehdijjz/Development/Projects/RAN
> npm i shelljs cli-clear

npm WARN gentlyRm not removing /Users/mehdijjz/Development/Projects/RAN/node_modules/webpack-bundle-analyzer/node_modules/.bin/acorn as it wasn't installed by /Users/mehdijjz/Development/Projects/RAN/node_modules/webpack-bundle-analyzer/node_modules/acorn

> pre-commit@1.2.2 uninstall /Users/mehdijjz/Development/Projects/RAN/node_modules/pre-commit
> node uninstall.js


> husky@0.14.2 uninstall /Users/mehdijjz/Development/Projects/RAN/node_modules/husky
> node ./bin/uninstall.js

husky
uninstalling Git hooks
done

npm WARN gentlyRm not removing /Users/mehdijjz/Development/Projects/RAN/node_modules/espree/node_modules/.bin/acorn as it wasn't installed by /Users/mehdijjz/Development/Projects/RAN/node_modules/espree/node_modules/acorn
npm notice created a lockfile as package-lock.json. You should commit this file.
+ shelljs@0.7.8
+ cli-clear@1.0.4
added 1 package, removed 1196 packages and updated 16 packages in 14.907s
module.js:487
    throw err;
    ^

Error: Cannot find module 'figlet'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mehdijjz/Development/Projects/RAN/helper_scripts/CL_commands/__helpers.js:1:78)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by Sly777** [comment]
Hey @mehdijjz, I found the bug on node.js v8. I don't know why It's uninstalling some packages on node.js v8. I will work on that.

**Comment by Sly777** [comment]
Last Update 😄 
I pushed hotfix for node.js v8 now. I tested on v8.1.3 and It works but can you also test it, please?

**Comment by mehdijjz** [comment]
@Sly777 yeah great it works thanks !
