### ISSUE TITLE
i can't run built code

### ISSUE THREAD

**Issue by samueljim** [Sly777/ran#295]
PS C:\Users\thesa\Documents\ia-jn> yarn run start
yarn run v1.1.0
$ cross-env NODE_ENV=production node ./node_modules/.bin/pm2 start server.js -i max --attach
C:\Users\thesa\Documents\ia-jn\node_modules\.bin\pm2:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Sly777** [comment]
Hey @samueljim, do you give information about your system such as node.js version, windows version, npm version, ran version,...etc?

**Comment by samueljim** [comment]
Windows 10 - 16299
Node 8.9.1 ( i also used 6 and 8.4)
I used the latest version of ran that i pulled the same week as the post

**Comment by johhansantana** [comment]
I think you need to run `yarn build` before `yarn start`

**Comment by samueljim** [comment]
I have done that many times
