### ISSUE TITLE
setup.js file gets deleted when I run `npm run setup` in the terminal

### ISSUE THREAD

**Issue by joshuaquek** [Sly777/ran#444]
When I run 

`npm run setup`

this file (setup.js) disappears and automatically gets deleted for some odd reason:

./helper_scripts/CL_commands/setup.js

Is there a reason for this? 

I am then unable to run `npm run setup` anymore after this happens.

**Comment by joshuaquek** [comment]
This is the output I am getting in the console

```
➜  RAN git:(master) ✗ npm run setup                                                                                                          [18/03/7| 3:01PM]

> ran-boilerplate@0.8.0 setup /Users/joshua.quek/Desktop/RAN
> node ./helper_scripts/CL_commands/setup.js && npm run setup:after
















  ____      _    _   _ _ 
 |  _ \    / \  | \ | | |
 | |_) |  / _ \ |  \| | |
 |  _ <  / ___ \| |\  |_|
 |_| \_\/_/   \_\_| \_(_)
                         

Cleaning RAN! for preparing new project...
Installing dependencies... (This might take a while)

Initialising new repository...





























RAN! is ready to go!


> ran-boilerplate@0.8.0 setup:after /Users/joshua.quek/Desktop/RAN
> npm run build


> ran-boilerplate@0.8.0 build /Users/joshua.quek/Desktop/RAN
> npm run clean-cache && next build


> ran-boilerplate@0.8.0 clean-cache /Users/joshua.quek/Desktop/RAN
> rimraf -rf ./node_modules/.cache

> Using external babel configuration
> Location: "/Users/joshua.quek/Desktop/RAN/.babelrc"
Failed to load ./public.env.
Failed to load ./public.env.
➜  RAN git:(master) npm run setup                                                                                                            [18/03/7| 3:02PM]

> ran-boilerplate@0.8.0 setup /Users/joshua.quek/Desktop/RAN
> node ./helper_scripts/CL_commands/setup.js && npm run setup:after

module.js:557
    throw err;
    ^

Error: Cannot find module '/Users/joshua.quek/Desktop/RAN/helper_scripts/CL_commands/setup.js'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ran-boilerplate@0.8.0 setup: `node ./helper_scripts/CL_commands/setup.js && npm run setup:after`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ran-boilerplate@0.8.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/joshua.quek/.npm/_logs/2018-03-07T07_03_06_127Z-debug.log
➜  RAN git:(master)                        
```

**Comment by guateandrew** [comment]
Same here. Any resolution?

**Comment by mukulhase** [comment]
Same

**Comment by Sly777** [comment]
Hey all, I was really busy with my personal stuff so I couldn't check this. So basically, I was removing this file because after run one time, There is no need to run it again (on my theory). I removed it on **beta** channel so you can test it with that change. Also, what is the scenario of the reason to run setup again? @joshuaquek @gabadi @guateandrew @mukulhase
