### ISSUE TITLE
Cannot convert object to primitive value

### ISSUE THREAD

**Issue by 10111DG** [Sly777/ran#639]
Hello! 

After clean Setup "**yarn && yarn setup:clean**" 
i started  **yarn dev**  and i got a  Compiled successfully in 2482ms .. 

But if i open in Browser the Project i got this error:

> TypeError: Cannot convert object to primitive value
    at String.concat (<anonymous>)
    at dump (/home/mondoshawan/Projects/digitalgeneralist/RAN/.next/server/static/development/pages/index.js:448:35)
    at /home/mondoshawan/Projects/digitalgeneralist/RAN/.next/server/static/development/pages/index.js:1032:798
    at processChild (/home/mondoshawan/Projects/digitalgeneralist/RAN/node_modules/react-dom/cjs/react-dom-server.node.development.js:2792:14)
    at resolve (/home/mondoshawan/Projects/digitalgeneralist/RAN/node_modules/react-dom/cjs/react-dom-server.node.development.js:2716:5)
    at ReactDOMServerRenderer.render (/home/mondoshawan/Projects/digitalgeneralist/RAN/node_modules/react-dom/cjs/react-dom-server.node.development.js:3100:22)
    at ReactDOMServerRenderer.read (/home/mondoshawan/Projects/digitalgeneralist/RAN/node_modules/react-dom/cjs/react-dom-server.node.development.js:3059:29)
    at renderToString (/home/mondoshawan/Projects/digitalgeneralist/RAN/node_modules/react-dom/cjs/react-dom-server.node.development.js:3526:27)
    at renderPage (/home/mondoshawan/Projects/digitalgeneralist/RAN/node_modules/next/dist/server/render.js:319:26)
    at Function._callee$ (/home/mondoshawan/Projects/digitalgeneralist/RAN/.next/server/static/development/pages/_document.js:313:24)
    at tryCatch (/home/mondoshawan/Projects/digitalgeneralist/RAN/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/mondoshawan/Projects/digitalgeneralist/RAN/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/home/mondoshawan/Projects/digitalgeneralist/RAN/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/home/mondoshawan/Projects/digitalgeneralist/RAN/.next/server/static/development/pages/_document.js:225:103)
    at _next (/home/mondoshawan/Projects/digitalgeneralist/RAN/.next/server/static/development/pages/_document.js:227:194)
    at /home/mondoshawan/Projects/digitalgeneralist/RAN/.next/server/static/development/pages/_document.js:227:364
Warning: <title> should not be used in _document.js's <Head>. https://err.sh/next.js/no-document-title

**Comment by maihungdev** [comment]
Upgrade react version !

**Comment by ruucm** [comment]
same here

**Comment by prKassad** [comment]
+1

**Comment by kevincastejon** [comment]
same here
